clear all; close all; clc; %#ok<*CLALL>

%% Docker attributes
setenv('DOCKER_EXEC', 'docker');            % The command to run docker.
setenv('FSL_IMG', 'topup:6.0.3-20210212');  % The name of the topup image.

%% Prepares topup
[status, cmd_out] = fsl('pwd', char('gen_fsl_docker.sh', 'gen_topup_docker.sh'), '*');

%% Run topup
fsl_topup('data/fmap/sub-s011_ses-baseline_dir-PA_epi_4topup.nii', ...
          'data/acq_params.txt', ...
          'data/b02b0.cnf', ...
          'topup_results');

%% Apply topup
fsl_applytopup('data/func/sub-s011_ses-baseline_task-AXcpt_bold_2topup.nii', ...
          '1', ...
          'data/acq_params.txt', ...
          'topup_results', ...
          'jac', ...
          'spline', ...
          'hifi_images');
