clear all; close all; clc;

%% Docker attributes
setenv("DOCKER_EXEC", "docker");            % The command to run docker.
setenv("FSL_IMG", "fsl:6.0.3-20210209");    % The name of the topup image.

%% Run topup
[status, cmd_out] = fsl("pwd", ["gen_fsl_docker.sh", "gen_topup_docker.sh"], ["*"]);
cmd_out

%% Define FSL function
% Call FSL from inside a docker image.
% Parameters
%   cmd (string) : The command to run inside the docker.
%   in_files (list[string]) : A list of the input files required by the
%       command.
%   out_patterns (list[string]) : A list of patterns matching all the 
%       output files of the command that must be saved.
% Returns
%   status (int) : The exit code of the call.
%   cmd_out (string) : The stdout of the call.
%   out_files (list[string]) : A list of output files generated by the
%       command.
% Notes
%   This function requires the 'DOCKER_EXEC' and 'FSL_IMG' environment
%   variables to be defined.
%   This function works in a temporary directory and copies all the
%   required input files into that directory.
function [status, cmd_out, out_files] = fsl(cmd, in_files, out_patterns)
    % Create temporary directory
    cwd = pwd;
    twd = tempname(tempdir);
    err = mkdir(twd);
    if err ~= 1
        status = 0;
        cmd_out = "Unable to create temporary directory";
        return
    end
    % Copy all the input files
    for i = 1 : length(in_files)
        copyfile(in_files(i), twd);
    end
    % Move to temporary directory
    cd(twd);
    % Run the FSL command
    docker_exec = getenv("DOCKER_EXEC");
    fsl_img = getenv("FSL_IMG");
    docker_cmd = join([docker_exec, "run", "--rm", "-w", "/tmp", "-v", strcat(twd, ":", "/tmp"), fsl_img])
    [status, cmd_out] = system(join([docker_cmd, cmd]));
    % Copy all the output files to the initial directory
    for i = 1 : length(out_patterns)
        movefile(out_patterns(i), fullfile(cwd, "data"));
    end
    % Clean temporary directory and go back to initial directory
    delete("*");
    cd(cwd);
    rmdir(twd);
    isfolder(twd)
end